config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'tos', to: 'pages#tos'
  get 'pp', to: 'pages#pp'
  get 'usage', to: 'pages#usage'
  get 'inquiry', to: 'pages#inquiry'
  resources :users, only: %i[new create]
  resources :posts do
    resources :comments, only: %i[create update destroy], shallow: true do
      resources :best_answers, only: %i[create destroy]
    end
    resource :closes, controller: 'posts/closes', only: %i[update]
    collection do
      get :favorites
      get :search
    end
    member do
      get :judgment
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :votes, only: %i[create destroy], shallow: true
  resource :mypage, only: %i[show edit update] do
    collection do
      get :post
      get :published
      get :draft
      get :closing
      get :trash
      get :untrash
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit show update destroy]
    resources :posts, only: %i[index edit show update destroy]
    resources :categories, only: %i[new create index edit show update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_answer.rb
class BestAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  with_options presence: true do
    validates :name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_one :best_answer

  with_options presence: true do
    validates :content
    validates :status
  end

  validates :content, length: { maximum: 65_535 }

  enum status: { unanswer: 0, trash: 1, untrash: 2 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :votes, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
    validates :status
    validates :deadline
  end

  enum status: { published: 0, draft: 1, closing: 2, trash: 3, untrash: 4 }

  scope :past_closing, -> { where('deadline <= ?', Time.current) }

  # 締切時間が過ぎているか
  def closed?
    Time.current >= deadline
  end

  # draft(下書き)であればreturn
  # 締切時間が過ぎていれば締切。過ぎていなければ公開のままにする
  def adjust_status
    return if draft?

    self.status = if closed?
                    :closing
                  else
                    :published
                  end
  end

  def message_on_closing
    if published?
      '記事を公開しました'
    elsif closing?
      '記事を締め切りました'
    end
  end

  def favorited_by(user)
    Favorite.find_by(user_id: user.id, post_id: id)
  end

  def voted_by(user)
    Vote.find_by(user_id: user.id, post_id: id)
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :votes, dependent: :destroy
  has_many :vote_posts, through: :votes, source: :post
  has_many :best_answers, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates_acceptance_of :agreement, allow_nil: false, on: :create

  validates :name, presence: true, length: { maximum: 255 }

  validates :email, uniqueness: true

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def favorite(post)
    favorites.create!(post_id: post.id)
  end

  def unfavorite(post)
    favorite_posts.delete(post)
  end

  def favorite?(post)
    Favorite.where(user_id: id, post_id: post.id).exists?
  end

  def unvote(post)
    vote_posts.delete(post)
  end

  def vote?(post)
    Vote.where(user_id: id, post_id: post.id).exists?
  end

  def best_answer(comment)
    favorites.create!(comment_id: comment.id)
  end

  def usually_answer(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).delete
  end

  def best_answer?(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).exists?
  end

  def best_count
    Comment.joins(:best_answer).where(user_id: id).count
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  with_options presence: true do
    validates :status
  end

  enum status: { unanswer: 0, trash: 1, untrash: 2 }

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit destroy]
  def create
    @comment = current_user.comments.create(comment_params)
    flash.now[:success] = (t '.success')
  end

  def edit; end

  def update
    @comment = current_user.comments.find(params[:id])
    if @comment.update(comment_update_params)
      render json: { comment: @comment }, status: :ok
    else
      render json: { comment: @comment, errors: { messages: @comment.errors.full_messages } }, status: :bad_request
    end
  end

  def destroy
    @comment = current_user.comments.find(params[:id]) # current_userのコメント
    @comment.destroy!
    flash.now[:success] = (t '.destroy')
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :status).merge(post_id: params[:post_id])
  end

  def set_comment
    @comment = Comment.find_by(id: params[:id])
  end

  def comment_update_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: %i[tos pp top usage]

  def tos; end

  def pp; end

  def top; end

  def usage; end

  def inquiry; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                   'RUNTEQ BOARD APP(管理画面)'
                 else
                   'RUNTEQ BOARD APP'
                 end

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def is_active_controller(controller_name)
    params[:controller] == controller_name ? 'active' : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? 'active' : nil
  end

  def is_active_actions(action_names)
    action_names.include?(params[:action]) ? 'active' : nil
  end

  def is_active_controller_and_action(controller_name, action_name)
    return unless params[:controller] == controller_name && params[:action] == action_name

    'active'
  end
end

app/helpers/best_answers_helper.rb
module BestAnswersHelper
end

app/helpers/catefories_helper.rb
module CateforiesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/closes_helper.rb
module ClosesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_best_answer.html.erb
<%= link_to comment_best_answers_path(comment_id: comment.id),
            id: "js-best_answer-button-for-comment-#{comment.id}",
            method: :post,
            remote: true do %>
  <%= icon 'far', 'star' %>
<% end %>

app/views/comments/_best_answer_button.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <li class="list-inline-item">
    <% if current_user.best_answer?(comment) %>
      <%= render 'comments/usually_answer', comment: comment %>
    <% else %>
      <%= render 'comments/best_answer', comment: comment %>
    <% end %>
  </li>
</ul>

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>" class="comment-<%= comment.status %>">
  <td>
    <h3 class="small"><%= t('posts.index.contributor') %> : <%= comment.user.name %></h3>
    <div id="js-comment-<%= comment.id %>">
      <%= simple_format(comment.status_i18n) %>
      <%= simple_format(comment.content) %>
    </div>
    <div id="js-textarea-comment-box-<%= comment.id %>" style="display: none;">
      <textarea id="js-textarea-comment-<%= comment.id %>" class="form-control mb-1"><%= comment.content %></textarea>
      <button class="btn btn-light js-button-edit-comment-cancel" data-comment-id="<%= comment.id %>"><%= (t 'posts.show.cancel') %></button>
      <button class="btn btn-success js-button-comment-update" data-comment-id="<%= comment.id %>"><%= (t 'posts.show.update') %></button>
    </div>
  </td>

  <% if logged_in? %>
    <% if current_user.own?(comment) %>
      <td class="action">
        <ul class="list-inline justify-content-center" style="float: right;">
          <li class="list-inline-item">
            <a href="#" class='js-edit-comment-button' data-comment-id="<%= comment.id %>">
              <%= icon 'fa', 'pen' %>
            </a>
          </li>
          <li class="list-inline-item">
            <%= link_to comment_path(comment), 
              id: 'js-delete-comment-button',
              method: :delete,
              data: { confirm: t('defaults.message.delete_confirm') },
              remote: true do %>
              <%= icon 'fas', 'trash' %>
            <% end %>
          </li>
        </ul>
      </td>
      <% elsif current_user.own?(@post) && @post.trash? || current_user.own?(@post) && @post.untrash? %>
      <td class="action">
        <ul class="list-inline justify-content-center" style="float: right;">
          <li class="list-inline-item">
            <%= render 'comments/best_answer_button', comment: comment %>
          </li>
        </ul>
      </td>
    <% end %>
  <% end %>
</tr>

app/views/comments/_comments.html.erb
<div class="row">
  <div class="col-lg-8 offset-lg-2">
    <table id="js-table-comment" class="table">
      <div><%= t('posts.index.total_comments') %>：<%= @post.comments.count %></div>
      <p><%= t('posts.index.trash') %>：<%= @post.comments.trash.count %>　<%= t('posts.index.untrash') %>：<%= @post.comments.untrash.count %></p>
      <%= render comments %>
    </table>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row mb-3">
  <div class="col-lg-8 offset-lg-2">
    <%= form_with model: comment, url: [post, comment], local: false,  id: 'new_comment' do |f| %>
      <%= f.label :status %> </br>
      <%= f.collection_radio_buttons :status, Vote.statuses_i18n.slice(:trash, :untrash), :first , :last %> </br>
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control mb-3', id: 'js-new-comment-content', row: 4, placeholder: Comment.human_attribute_name(:content) %>
      <%= f.submit t('defaults.post'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/_usually_answer.html.erb
<%= link_to best_answer_path(current_user.best_answers.find_by(comment_id: comment.id)),
            id: "js-favorite-button-for-comment-#{comment.id}",
            method: :delete,
            remote: true do %>
  <%= icon 'fas', 'star' %>
<% end %>

app/views/comments/create.js.erb
$("#error_messages").remove()
<% if @comment.errors.present? %>
  $("#new_comment").prepend("<%= j(render('shared/error_messages', object: @comment)) %>")
<% else %>
  $("#new_comment").prepend("<%= j(render 'shared/flash_message') %>")
  $("#js-table-comment").prepend("<%= j(render('comments/comment', comment: @comment)) %>")
  $("#js-new-comment-content").val('')
<% end %>

app/views/comments/destroy.js.erb
$("#new_comment").prepend("<%= j(render 'shared/flash_message') %>")
$("#comment-<%= @comment.id %>").remove();