config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'tos', to: 'pages#tos'
  get 'pp', to: 'pages#pp'
  get 'usage', to: 'pages#usage'
  get 'inquiry', to: 'pages#inquiry'
  resources :users, only: %i[new create]
  resources :posts do
    resources :comments, only: %i[create update destroy], shallow: true do
      resources :best_answers, only: %i[create destroy]
    end
    resource :closes, controller: 'posts/closes', only: %i[update]
    collection do
      get :favorites
      get :search
    end
    member do
      get :judgment
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :votes, only: %i[create destroy], shallow: true
  resource :mypage, only: %i[show edit update] do
    collection do
      get :post
      get :published
      get :draft
      get :closing
      get :trash
      get :untrash
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit show update destroy]
    resources :posts, only: %i[index edit show update destroy]
    resources :categories, only: %i[new create index edit show update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_answer.rb
class BestAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  with_options presence: true do
    validates :name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_one :best_answer

  with_options presence: true do
    validates :content
    validates :status
  end

  validates :content, length: { maximum: 65_535 }

  enum status: { unanswer: 0, trash: 1, untrash: 2 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :votes, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
    validates :status
    validates :deadline
  end

  enum status: { published: 0, draft: 1, closing: 2, trash: 3, untrash: 4 }

  scope :past_closing, -> { where('deadline <= ?', Time.current) }

  # 締切時間が過ぎているか
  def closed?
    Time.current >= deadline
  end

  # draft(下書き)であればreturn
  # 締切時間が過ぎていれば締切。過ぎていなければ公開のままにする
  def adjust_status
    return if draft?

    self.status = if closed?
                    :closing
                  else
                    :published
                  end
  end

  def message_on_closing
    if published?
      '記事を公開しました'
    elsif closing?
      '記事を締め切りました'
    end
  end

  def favorited_by(user)
    Favorite.find_by(user_id: user.id, post_id: id)
  end

  def voted_by(user)
    Vote.find_by(user_id: user.id, post_id: id)
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :votes, dependent: :destroy
  has_many :vote_posts, through: :votes, source: :post
  has_many :best_answers, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates_acceptance_of :agreement, allow_nil: false, on: :create

  validates :name, presence: true, length: { maximum: 255 }

  validates :email, uniqueness: true

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def favorite(post)
    favorites.create!(post_id: post.id)
  end

  def unfavorite(post)
    favorite_posts.delete(post)
  end

  def favorite?(post)
    Favorite.where(user_id: id, post_id: post.id).exists?
  end

  def unvote(post)
    vote_posts.delete(post)
  end

  def vote?(post)
    Vote.where(user_id: id, post_id: post.id).exists?
  end

  def best_answer(comment)
    favorites.create!(comment_id: comment.id)
  end

  def usually_answer(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).delete
  end

  def best_answer?(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).exists?
  end

  def best_count
    Comment.joins(:best_answer).where(user_id: id).count
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  with_options presence: true do
    validates :status
  end

  enum status: { unanswer: 0, trash: 1, untrash: 2 }

  validates :user_id, uniqueness: { scope: :post_id }
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                   'RUNTEQ BOARD APP(管理画面)'
                 else
                   'RUNTEQ BOARD APP'
                 end

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def is_active_controller(controller_name)
    params[:controller] == controller_name ? 'active' : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? 'active' : nil
  end

  def is_active_actions(action_names)
    action_names.include?(params[:action]) ? 'active' : nil
  end

  def is_active_controller_and_action(controller_name, action_name)
    return unless params[:controller] == controller_name && params[:action] == action_name

    'active'
  end
end

app/helpers/catefories_helper.rb
module CateforiesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/closes_helper.rb
module ClosesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta lang='ja'>
  <meta name="robots" content="noindex, nofollow">
  <title><%= page_title(yield(:title), admin: true) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <%= render 'admin/shared/header' %>
  <%= render 'admin/shared/sidebar' %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </div>
  <!-- /.content-wrapper -->

  <%= render 'admin/shared/footer' %>

</div>
<%= javascript_pack_tag 'admin' %>
</body>
</html>

app/views/shared/_before_login_header.html.erb
<nav class="navbar navbar-expand-lg navbar-default sticky-top">
  <div class="container-fluid">
    <%= link_to posts_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo-dansyaryu', :size =>'160x40' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item d-flex align-items-center">
          <%= link_to t('defaults.posts'), posts_path, class: 'btn btn-primary btn-sm me-2' %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to t('defaults.register'), new_user_path, class: 'btn btn-primary btn-sm me-2' %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to t('defaults.login'), login_path, class: 'btn btn-primary btn-sm me-2' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <ul>
        <li class="nonmark"><%= link_to t('defaults.what_dansyaryu?'), root_path %><l/i>
        <li class="nonmark"><%= link_to t('defaults.how_to_use_site'), usage_path %><l/i>
        <li class="nonmark"><%= link_to t('users.new.terms_of_service'), tos_path %><l/i>
        <li class="nonmark"><%= link_to t('users.new.privacy_policy'), pp_path %><l/i>
        <li class="nonmark"><%= link_to t('defaults.inquiry'), inquiry_path %><l/i>
      </ul>
    </div>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-default sticky-top">
  <div class="container-fluid">
    <%= link_to posts_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo-dansyaryu', :size =>'160x40' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item d-flex align-items-center">
          <%= link_to t('defaults.posts'), posts_path, class: 'btn btn-primary btn-sm me-2' %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <%= link_to t('posts.new.title'), new_post_path, class: 'btn btn-primary btn-sm me-2' %>
        </li>
        <li class="nav-item d-flex align-items-center">
          <p class="rounded-circle gin" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
            <%= t('users.new.user_name') %>:<%= current_user.name %>
          </p>
        </li>
        <li class="dropdown ms-2 d-flex">
          <p class="gin" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
            <i class="fa-solid fa-gear fa-lg"></i>
          </p>
          <div class="dropdown-menu dropdown-menu-end">
            <div class="dropdown-item">
              <div class="d-flex">
                <div class="ms-3 lh-1">
                  <h5 class="mb-1"><%= current_user.name %></h5>
                  <p class="mb-0 text-muted"><%= current_user.email %></p>
                </div>
              </div>
            </div>
            <div class="dropdown-divider"></div>
            <ul class="list-unstyled">
              <li>
                <a class="dropdown-item" href="/mypage">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.mypage') %>
                </a>
              </li>
            </ul>
            <div class="dropdown-divider"></div>
            <ul class="list-unstyled">
              <li>
                <a class="dropdown-item" href="/mypage/post">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.my_posts') %>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="/mypage/published">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.wanted_posts') %>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="/mypage/draft">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.draft_posts') %>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="/mypage/closing">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.closing_posts') %>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="/mypage/trash">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.trash_posts') %>
                </a>
              </li>
              <li>
                <a class="dropdown-item" href="/mypage/untrash">
                  <i class="bi bi-person me-2"></i><%= t('mypages.show.untrash_posts') %>
                </a>
              </li>
            </ul>
            <div class="dropdown-divider"></div>
            <ul class="list-unstyled">
              <li>
                <%= link_to logout_path, method: :get, data: { confirm: t('defaults.message.logout?') }, class: 'dropdown-item' do %>
                  <i class="bi bi-box-arrow-left me-2"></i><%= t('defaults.logout') %>
                <% end %>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<li class="dropdown d-inline-block stopevent">
  <div class="dropdown-menu dropdown-menu-end dropdown-menu-lg" aria-labelledby="dropdownNotificationSecond">
    <div>
      <div class="border-bottom px-3 pb-3 d-flex justify-content-between align-items-center">
        <span class="h5 mb-0">Notifications</span>
        <a href="# " class="text-muted"><span class="align-middle"><i class="fe fe-settings me-1"></i></span></a>
      </div>
      <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 300px;">
        <ul class="list-group list-group-flush notification-list-scroll " style="overflow-y: scroll; width: auto; height: 300px;">
        </ul>
        <div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 154.905px;"></div>
        <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div>
      </div>
      <div class="border-top px-3 pt-3 pb-0">
        <a href="/mypage/notifications" class="text-link fw-semi-bold">See all Notifications</a>
      </div>
    </div>
  </div>
</li>

app/views/shared/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'logo-dansyaryu', :size =>'250x50' %>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
      </div>
      <div class="info">
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/posts')}" do %>
            <p>
              <%= "新規投稿" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/users')}" do %>
            <p>
              <%= "投稿済み" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/categories')}" do %>
            <p>
              <%= "下書き" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/categories')}" do %>
            <p>
              <%= "お気に入り" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/categories')}" do %>
            <p>
              <%= "捨てたもの" %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to '#', class: "nav-link #{is_active_controller('admin/categories')}" do %>
            <p>
              <%= "捨てなかったもの" %>
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>