config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'tos', to: 'pages#tos'
  get 'pp', to: 'pages#pp'
  get 'usage', to: 'pages#usage'
  get 'inquiry', to: 'pages#inquiry'
  resources :users, only: %i[new create]
  resources :posts do
    resources :comments, only: %i[create update destroy], shallow: true do
      resources :best_answers, only: %i[create destroy]
    end
    resource :closes, controller: 'posts/closes', only: %i[update]
    collection do
      get :favorites
      get :search
    end
    member do
      get :judgment
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :votes, only: %i[create destroy], shallow: true
  resource :mypage, only: %i[show edit update] do
    collection do
      get :post
      get :published
      get :draft
      get :closing
      get :trash
      get :untrash
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit show update destroy]
    resources :posts, only: %i[index edit show update destroy]
    resources :categories, only: %i[new create index edit show update destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :votes, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
    validates :status
    validates :deadline
  end

  enum status: { published: 0, draft: 1, closing: 2, trash: 3, untrash: 4 }

  scope :past_closing, -> { where('deadline <= ?', Time.current) }

  # 締切時間が過ぎているか
  def closed?
    Time.current >= deadline
  end

  # draft(下書き)であればreturn
  # 締切時間が過ぎていれば締切。過ぎていなければ公開のままにする
  def adjust_status
    return if draft?

    self.status = if closed?
                    :closing
                  else
                    :published
                  end
  end

  def message_on_closing
    if published?
      '記事を公開しました'
    elsif closing?
      '記事を締め切りました'
    end
  end

  def favorited_by(user)
    Favorite.find_by(user_id: user.id, post_id: id)
  end

  def voted_by(user)
    Vote.find_by(user_id: user.id, post_id: id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def bookmarks
    @q = current_user.bookmark_posts.ransack(params[:q])
    @bookmark_posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def search
    @results = @q.result
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('.success')
    else
      flash.now[:danger] = (t '.fail')
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to admin_post_path, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to admin_posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :body, :img, :img_cache, :deadline).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_post, only: %i[edit update judgment destroy]
  before_action :ensure_user, only: %i[edit update judgment destroy]

  def index
    @categories = Category.all
    @q = Post.where.not(status: :draft).ransack(params[:q])
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @posts = @category.posts.where.not(status: :draft).order(created_at: :desc).page(params[:page])
    else
      @posts = @q.result(distinct: true).includes(:user, :comments).order(created_at: :desc).page(params[:page])
    end
  end

  def favorites
    @categories = Category.all
    @q = current_user.favorite_posts.where.not(status: :draft).ransack(params[:q])
    @favorite_posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def drafts
    @categories = Category.all
    @q = current_user.posts.where(status: :draft).ransack(params[:q])
    @draft_posts = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def search
    @results = @q.result
  end

  def judgment; end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: t('.success')
    else
      flash.now[:danger] = (t '.fail')
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @vote = Vote.find_by(post: @post, user: current_user) || Vote.new
    if @post.draft?
      ensure_user
    end
  end

  def edit; end

  def update
    authorize(@post)

    @post.assign_attributes(post_params)
    @post.adjust_status
    if @post.update(post_params)
      redirect_to @post, success: t('defaults.message.updated', item: Post.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: Post.model_name.human)
      render :edit
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, success: t('defaults.message.deleted', item: Post.model_name.human)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = current_user.posts.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :body, :img, :img_cache, { category_ids: [] }, :status,
                                 :deadline).merge(user_id: current_user.id)
  end

  def ensure_user
    @post = Post.find_by(id: params[:id])
    return unless @post.user_id != @current_user.id

    redirect_to posts_path
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_delete_trash.html.erb
<%= link_to vote_path(current_user.votes.find_by(post_id: post.id)),
            id: "js-trash-button-for-post-#{post.id}",
            method: :delete,
            remote: true do %>
  <%= "投票を撤回する" %>
<% end %>

app/views/posts/_delete_untrash.html.erb
<%= link_to vote_path(current_user.votes.find_by(post_id: post.id)),
            id: "js-untrash-button-for-post-#{post.id}",
            method: :delete,
            remote: true do %>
  <%= "投票を撤回する" %>
<% end %>

app/views/posts/_delete_vote.html.erb
<%= link_to vote_path(current_user.votes.find_by(post_id: post.id)),
            id: "js-delete-vote-button-for-post-#{post.id}",
            method: :delete,
            remote: true do %>
  <%= "投票を撤回する" %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :'title', class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :img %>
  <%= f.file_field :img, onchange: 'previewFileWithId(preview)', class: 'form-control mb-3', accept: 'image/*' %>
  <%= f.hidden_field :img_cache %>
  </div>
  <div class='mt-3 mb-3'>
    <%= image_tag post.img.url,
                  id: 'preview',
                  size: '300x200' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :'body', class: "form-control", rows: 10 %>
  </div>
  <div class="form-group">
    <%= f.label :category %> </br>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
      <%= category.label do %>
        <%= category.check_box %>
        <%= category.text %>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :status %> </br>
    <%= f.collection_radio_buttons :status, Post.statuses_i18n.slice(:published, :draft), :first , :last %>
  </div>
  <% if post.deadline.blank? %>
    <div class="form-group">
      <%= f.label :deadline %>
      <%= f.datetime_field :deadline, class: 'form-control', min: Date.today, value: Time.current.since(1.week).strftime('%Y-%m-%dT12:00') %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.label :deadline %>
      <%= f.datetime_field :deadline, class: 'form-control', min: Date.today %>
    </div>
  <% end %>
  <%= f.submit (t 'defaults.register'), class: "btn btn-primary", name: 'commit' %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="card">
      <%= image_tag post.img_url, size: '300x200', class: 'card-img-top'%>
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to post.title, post_path(post) %>
        </h4>
        <% if logged_in? %>
          <% if current_user.own?(post) %>
            <%= render 'crud_menus', post: post %>
          <% end %>
        <% end %>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= icon 'far', 'user' %>
            <%= post.user.name %>
          </li></br>
          <li class="list-inline-item">
            <%= t('posts.index.posting_date') %>：
            <%= l(post.created_at, format: :short) %>
          </li></br>
          <li class="list-inline-item">
            <%= t('categories.category') %>：
            <% post.categories.each do |item| %>
              <%= item.name %>
            <% end %>
          </li></br>
          <li class="list-inline-item">
            <%= t('posts.index.status') %>：
            <%= post.status_i18n %>
          </li></br>
          <li class="list-inline-item">
            <%= t('posts.index.deadline') %>：
            <%= l post.deadline, format: :short %>
          </li></br>
          <li class="list-inline-item">
            <%= t('posts.index.total_comments') %>
            <%= post.comments.count %>
          </li>
        </ul>
        <p class="card-text"><%= post.body.truncate(20) %></p>
      </div>
    </div>
  </div>
</div>

app/views/posts/_trash.html.erb
<%= link_to votes_path(post_id: post.id, status: 'trash'),
            id: "js-trash-button-for-post-#{post.id}",
            method: :post,
            remote: true do %>
  <%= "捨てていい" %>
<% end %>

app/views/posts/_unvote.html.erb
<p><%= @vote.status_i18n %><%= t('posts.index.voted') %></p>
<%= link_to vote_path(current_user.votes.find_by(post_id: post.id)),
            id: "js-unvote-button-for-post-#{post.id}",
            method: :delete,
            remote: true do %>
  <%= t('posts.index.withdraw_vote') %>
<% end %>

app/views/posts/_update_untrash.html.erb
<%= link_to vote_path(post_id: post.id, status: 'untrash'),
            id: "js-untrash-button-for-post-#{post.id}",
            method: :patch,
            remote: true do %>
  <%= "やっぱり捨てないで" %>
<% end %>

app/views/posts/_vote_button.html.erb
<ul class='crud-menu-btn list-inline float-right', id=<%= "js-vote-button-for-post-#{@post.id}" %>>
  <li class="list-inline-item">
    <% if current_user.vote?(post) %>
      <%= render 'posts/unvote', post: post %>
    <% else %>
      <%= render 'posts/vote', post: post %>
    <% end %>
  </li>
</ul>

app/views/posts/_vote_counter.html.erb
<ul class='crud-menu-btn list-inline float-right', id=<%= "js-vote-counter-for-post-#{@post.id}" %>>
  <li class="list-inline-item"><%= t('posts.index.trash') %><%= post.votes.trash.count %></li>
  <li class="list-inline-item"><%= t('posts.index.untrash') %><%= post.votes.untrash.count %></li>
</ul>

app/views/posts/drafts.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <%= render 'search_form', url: drafts_posts_path %>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @draft_posts.present? %>
          <%= render @draft_posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <%= paginate @draft_posts %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <%= render 'search_form', url: posts_path %>
      </form>
    </div>
  </div>

  <h3 class="side-title"><%= t('categories.category') %></h3>
  <ul class="col-md-4 list-unstyled d-flex">
    <% @categories.each do |category| %>
      <li class="mar">
        <%= link_to category.name, posts_path(category_id: category.id) %>
      </li>
    <% end %>
  </ul>
  
  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <%= render @posts %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
      <!-- ページネーション -->
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/posts/judgment.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <div class='row'>
            <div class='col-md-3'>
              <%= image_tag @post.img.url, class: 'card-img-top img-fluid', size: '300x200' %>
            </div>
            <div class='col-md-9'>
              <h3 class="d-inline"><%= @post.title %></h3>
              <% if current_user.own?(@post) %>
                <ul class='crud-menu-btn list-inline float-right', id=<%= "js-vote-button-for-post-#{@post.id}" %>>
                  <li class="list-inline-item"><%= t('posts.index.trash') %><%= @post.votes.trash.count %></li>
                  <li class="list-inline-item"><%= t('posts.index.untrash') %><%= @post.votes.untrash.count %></li>
                </ul>
              <% else %>
                <div class="row mb-3">
                  <div class="col-lg-8 offset-lg-2">
                    <%= form_with model: @vote, url: [@post, @vote], id: 'new_vote' do |f| %>
                      <%= f.label :status %>
                      <%= f.select :status, Vote.statuses.keys.map {|k| [I18n.t("enums.vote.status.#{k}"), k]} %>
                      <%= f.submit t('defaults.post'), class: 'btn btn-primary' %>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <ul class="list-inline">
                <li class="list-inline-item"><%= t('posts.index.contributor') %>：<%= @post.user.name %></li><br>
                <li class="list-inline-item"><%= t('posts.index.posting_date') %>：<%= l @post.created_at, format: :short %></li></br>
                <li class="list-inline-item">
                  <%= t('categories.category') %>：
                  <% @post.categories.each do |item| %>
                    <%= item.name %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
          <p><%= simple_format(@post.body) %></p>
          <%= form_with model: @post, local: true do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="form-group">
              <%= f.label :status %> </br>
              <%= f.collection_radio_buttons :status, Post.statuses_i18n.slice(:trash, :untrash), :first , :last %>
            </div>
            <%= f.submit (t 'posts.index.judgment'), class: "btn btn-primary", name: 'commit' %>
          <% end %>
        </div>
      </article>
    </div>
  </div>
  

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= render 'form', { post: @post } %>
    </div>
  </div>
</div>