config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root to: 'pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'tos', to: 'pages#tos'
  get 'pp', to: 'pages#pp'
  get 'usage', to: 'pages#usage'
  get 'inquiry', to: 'pages#inquiry'
  resources :users, only: %i[new create]
  resources :posts do
    resources :comments, only: %i[create update destroy], shallow: true do
      resources :best_answers, only: %i[create destroy]
    end
    resource :closes, controller: 'posts/closes', only: %i[update]
    collection do
      get :favorites
      get :search
    end
    member do
      get :judgment
    end
  end
  resources :favorites, only: %i[create destroy]
  resources :votes, only: %i[create destroy], shallow: true
  resource :mypage, only: %i[show edit update] do
    collection do
      get :post
      get :published
      get :draft
      get :closing
      get :trash
      get :untrash
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    get 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[index edit show update destroy]
    resources :posts, only: %i[index edit show update destroy]
    resources :categories, only: %i[new create index edit show update destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best_answer.rb
class BestAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :post_categories
  has_many :posts, through: :post_categories

  with_options presence: true do
    validates :name
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_one :best_answer

  with_options presence: true do
    validates :content
    validates :status
  end

  validates :content, length: { maximum: 65_535 }

  enum status: { unanswer: 0, trash: 1, untrash: 2 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :votes, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
    validates :status
    validates :deadline
  end

  enum status: { published: 0, draft: 1, closing: 2, trash: 3, untrash: 4 }

  scope :past_closing, -> { where('deadline <= ?', Time.current) }

  # 締切時間が過ぎているか
  def closed?
    Time.current >= deadline
  end

  # draft(下書き)であればreturn
  # 締切時間が過ぎていれば締切。過ぎていなければ公開のままにする
  def adjust_status
    return if draft?

    self.status = if closed?
                    :closing
                  else
                    :published
                  end
  end

  def message_on_closing
    if published?
      '記事を公開しました'
    elsif closing?
      '記事を締め切りました'
    end
  end

  def favorited_by(user)
    Favorite.find_by(user_id: user.id, post_id: id)
  end

  def voted_by(user)
    Vote.find_by(user_id: user.id, post_id: id)
  end
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :votes, dependent: :destroy
  has_many :vote_posts, through: :votes, source: :post
  has_many :best_answers, dependent: :destroy

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates_acceptance_of :agreement, allow_nil: false, on: :create

  validates :name, presence: true, length: { maximum: 255 }

  validates :email, uniqueness: true

  enum role: { general: 0, admin: 1 }

  def own?(object)
    id == object.user_id
  end

  def favorite(post)
    favorites.create!(post_id: post.id)
  end

  def unfavorite(post)
    favorite_posts.delete(post)
  end

  def favorite?(post)
    Favorite.where(user_id: id, post_id: post.id).exists?
  end

  def unvote(post)
    vote_posts.delete(post)
  end

  def vote?(post)
    Vote.where(user_id: id, post_id: post.id).exists?
  end

  def best_answer(comment)
    favorites.create!(comment_id: comment.id)
  end

  def usually_answer(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).delete
  end

  def best_answer?(comment)
    BestAnswer.where(user_id: id, comment_id: comment.id).exists?
  end

  def best_count
    Comment.joins(:best_answer).where(user_id: id).count
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post

  with_options presence: true do
    validates :status
  end

  enum status: { unanswer: 0, trash: 1, untrash: 2 }

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: %i[edit update destroy]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).order(created_at: :desc).page(params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path, success: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:danger] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to admin_users_path, success: t('defaults.message.deleted', item: User.model_name.human)
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login, only: %i[tos pp top usage]

  def tos; end

  def pp; end

  def top; end

  def usage; end

  def inquiry; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :agreement)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '', admin = false)
    base_title = if admin
                   'RUNTEQ BOARD APP(管理画面)'
                 else
                   'RUNTEQ BOARD APP'
                 end

    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def is_active_controller(controller_name)
    params[:controller] == controller_name ? 'active' : nil
  end

  def is_active_action(action_name)
    params[:action] == action_name ? 'active' : nil
  end

  def is_active_actions(action_names)
    action_names.include?(params[:action]) ? 'active' : nil
  end

  def is_active_controller_and_action(controller_name, action_name)
    return unless params[:controller] == controller_name && params[:action] == action_name

    'active'
  end
end

app/helpers/best_answers_helper.rb
module BestAnswersHelper
end

app/helpers/catefories_helper.rb
module CateforiesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/closes_helper.rb
module ClosesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admin/users/_search_form.html.erb
<%= search_form_for @q, url: admin_users_path do |f| %>
  <div class="row">
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto">
        <%= f.search_field :name_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
      </div>
      <div class="col-auto">
        <%= f.select :role_eq, User.roles_i18n.invert.map{|key, value| [key, User.roles[value]]}, { include_blank: t('defaults.unspecified') }, { class: 'form-control mr-1' } %>
      </div>
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.role_i18n %>
  </td>
  <td>
    <%= l user.created_at, format: :short %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_user_path(user), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_user_path(user), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_user_path(user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t '.title' %></h1>
      <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, User.roles_i18n.invert, {}, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= User.human_attribute_name(:id) %></th>
          <th scope="col"><%= User.human_attribute_name(:name) %></th>
          <th scope="col"><%= User.human_attribute_name(:role) %></th>
          <th scope="col"><%= User.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_user_path(@user), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_user_path(@user), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= User.human_attribute_name(:id) %></th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:name) %></th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:role) %></th>
          <td><%= @user.role_i18n %></td>
        </tr>
        <tr>
          <th scope="row"><%= User.human_attribute_name(:created_at) %></th>
          <td><%= l @user.created_at, format: :short %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container d-flex flex-column">
  <div class="row align-items-center justify-content-center g-0 min-vh-100">
    <div class="col-lg-5 col-md-8 py-8 py-xl-0">
      <!-- Card -->
      <div class="card shadow">
        <!-- Card body -->
        <div class="card-body p-6">
          <div class="mb-4">
            <h1 class="mb-1 fw-bold"><%= t('users.new.title') %></h1>
            <span><%= t('users.new.already_have_an_account?') %>
              <%= link_to t('users.new.to_login_page'), login_path, class: 'ms-1' %>
            </span>
          </div>
          <!-- Form -->
          <%= form_with model: @user do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="mb-3">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="mb-3">
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>
            </div>
            <div class="mb-3">
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="mb-3">
              <%= f.label :password_confirmation %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
            <div class="mb-3">
              <div class="form-check">
              <%= f.check_box :agreement, :as => :boolean, checked:false %>
                <span>私は <%= link_to t('users.new.terms_of_service'), tos_path %> と
											<%= link_to t('users.new.privacy_policy'), pp_path %>
                に同意します。</span></label>
              </div>
            </div>
            <div class="d-grid">
              <%= f.submit t('defaults.register'), class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>